import type { Post } from './posts';

// Posts are added here as content is migrated from hyppohq.ai/blog
// Run fetch agent to populate content for each slug
export const posts: Post[] = [
  {
    slug: 'why-sticky-notes-and-notebooks-dont-scale',
    title: 'Why Sticky Notes and Notebooks Don\'t Scale for Modern Service Businesses',
    date: 'April 3, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Sticky notes and notebooks feel productive — until a lead falls through a crack or a task gets forgotten. Here\'s why they don\'t scale.',
    content: '',
  },
  {
    slug: 'why-editing-speed-matters-more-than-perfection',
    title: 'Why Editing Speed Matters More Than Perfection in Content',
    date: 'March 28, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Waiting for the perfect post means posting less. Here\'s why speed beats perfection for small business content.',
    content: '',
  },
  {
    slug: 'why-businesses-are-harder-to-reach-than-they-think',
    title: 'Why Many Businesses Are Harder to Reach Than They Think',
    date: 'March 21, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Most business owners think they\'re easy to contact. Their customers often disagree. Here\'s what gets in the way.',
    content: '',
  },
  {
    slug: 'how-modern-businesses-handle-repetitive-tasks-differently',
    title: 'How Modern Businesses Handle Repetitive Tasks Differently',
    date: 'March 14, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'The businesses growing fastest aren\'t working harder — they\'ve removed themselves from the repetitive work entirely.',
    content: '',
  },
  {
    slug: 'how-ai-automations-follow-ups-and-apis-connect',
    title: 'How AI, Automations, Follow-Ups, and APIs Connect',
    date: 'March 7, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'AI doesn\'t work alone. It connects with automations, follow-up sequences, and APIs to build systems that run without you.',
    content: '',
  },
  {
    slug: 'how-hyppocrm-helps-businesses-stay-organized-without-spreadsheets',
    title: 'How HyppoCRM Helps Businesses Stay Organized Without Spreadsheets',
    date: 'February 28, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Spreadsheets break down when your business grows. HyppoCRM keeps everything in one place — automatically.',
    content: '',
  },
  {
    slug: 'how-to-talk-to-chatgpt-like-an-employee',
    title: 'How to Talk to ChatGPT Like an Employee',
    date: 'February 21, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Most people use ChatGPT like a search engine. The results are better when you treat it like a new hire who needs direction.',
    content: '',
  },
  {
    slug: 'why-forms-are-the-front-door-to-systems',
    title: 'Why Forms Are the Front Door to Systems',
    date: 'February 14, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'A form isn\'t just a way to collect info — it\'s the trigger that starts every automation in your business.',
    content: '',
  },
  {
    slug: 'how-ai-video-fits-into-modern-marketing-systems',
    title: 'How AI Video Fits Into Modern Marketing Systems',
    date: 'February 7, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'AI-generated video makes consistent content possible without a camera, a crew, or a recording schedule.',
    content: '',
  },
  {
    slug: 'how-automated-file-handling-saves-time-quietly',
    title: 'How Automated File Handling Saves Time Quietly',
    date: 'January 31, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Nobody talks about file handling — but the time lost to it adds up fast. Automation fixes it in the background.',
    content: '',
  },
  {
    slug: 'automatic-file-naming-and-sorting-explained',
    title: 'Automatic File Naming and Sorting Explained',
    date: 'January 24, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Inconsistent file names and cluttered folders slow everything down. Here\'s how automatic sorting removes the problem.',
    content: '',
  },
  {
    slug: 'why-chatgpt-needs-to-know-the-target-audience',
    title: 'Why ChatGPT Needs to Know the Target Audience',
    date: 'January 17, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Generic prompts produce generic output. Tell ChatGPT exactly who it\'s writing for and everything gets sharper.',
    content: '',
  },
  {
    slug: 'ai-generated-video-without-recording',
    title: 'AI-Generated Video Without Recording',
    date: 'January 10, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'You don\'t need to be on camera to have a video presence. AI avatar tools handle the recording for you.',
    content: '',
  },
  {
    slug: 'what-zapier-does-best-and-where-it-starts-to-break',
    title: 'What Zapier Does Best and Where It Starts to Break',
    date: 'January 3, 2026',
    author: 'Joseph Sestito III',
    excerpt: 'Zapier is powerful for simple connections between tools — but there\'s a ceiling. Here\'s where it works and where it doesn\'t.',
    content: '',
  },
  {
    slug: 'why-scheduling-is-a-system-problem',
    title: 'Why Scheduling Is a System Problem',
    date: 'December 27, 2025',
    author: 'Joseph Sestito III',
    excerpt: 'Scheduling chaos isn\'t a calendar problem — it\'s a systems problem. Here\'s how to fix the root cause.',
    content: '',
  },
  {
    slug: 'how-automation-helps-owners-step-out-of-the-weeds',
    title: 'How Automation Helps Owners Step Out of the Weeds',
    date: 'December 20, 2025',
    author: 'Joseph Sestito III',
    excerpt: 'Most business owners are stuck doing work their business should be doing. Automation creates the exit.',
    content: '',
  },
  {
    slug: 'real-reason-leads-go-cold-so-fast',
    title: 'The Real Reason Leads Go Cold So Fast',
    date: 'December 13, 2025',
    author: 'Joseph Sestito III',
    excerpt: 'Speed is the most important factor in lead conversion — and most businesses are too slow to respond.',
    content: '',
  },
  {
    slug: 'ai-image-generators-small-business-use-cases',
    title: 'AI Image Generators: Small Business Use Cases',
    date: 'December 6, 2025',
    author: 'Joseph Sestito III',
    excerpt: 'AI image generators aren\'t just for artists. Here\'s how small businesses are using them to replace design costs.',
    content: '',
  },
  {
    slug: 'why-chatgpt-context-matters-more-than-better-questions',
    title: 'Why ChatGPT Context Matters More Than Better Questions',
    date: 'November 29, 2025',
    author: 'Joseph Sestito III',
    excerpt: 'The prompt isn\'t the problem. The missing context is. Here\'s how to give ChatGPT what it actually needs.',
    content: '',
  },
];
